config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: :show

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = @restaurant.reviews.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1> RESTAURANTS </h1>
  <% @restaurants.each do |restaurant| %>
  <p><%= link_to restaurant_path(restaurant) do %> <%= restaurant.name %> <% end %>
  <%end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <% @restaurant.reviews.each do |review| %>
   <p><%= review.rating %></p>
   <p><%= review.content %></p>
  <% end %>
  <%= link_to "Add review", new_restaurant_review_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :rating, collection: 0..5, as: :select %>
  <%= f.input :content %>
  <%= f.button :submit, 'Submit Review' %>
<% end %>